services:
  ros2-jazzy:
    build: .
    container_name: simple-mapping-jig
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      - DISPLAY=${DISPLAY}
      - ROS_DOMAIN_ID=0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all,graphics,display
    volumes:
      - ./workspace:/ros2_ws/src
      - ./build:/ros2_ws/build
      - ./install:/ros2_ws/install
      - ./log:/ros2_ws/log
      - ./maps:/ros2_ws/maps
      - ./config/.bash_history:/root/.bash_history
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
    stdin_open: true
    tty: true
    restart: unless-stopped